Algoritmo "nomidade"

Var
nome15, nome20:caractere
idade15, idade20, mult:real


Inicio
escreval("Insira o primeiro nome")
leia(nome15)
escreval("Insira o segundo nome")
leia(nome20)
escreval("Insira a primeira idade")
leia(idade15)
escreval("Insira a segunda idade")
leia(idade20)

mult <- (idade15 * idade20);

escreval("A multiplicacao das idades de ",nome15," e ",nome20," e igual a ",mult)


Fimalgoritmo